[main]
font=FiraCode Nerd Font:size=11

[colors]
background=1c2127
foreground=c8d4dc
cursor=1c2127 c8d4dc

# Normal colors
regular0=1c2127
regular1=c96a6a
regular2=7ab87a
regular3=c9a84c
regular4=6878a0
regular5=8a7ab8
regular6=5fb3b3
regular7=c8d4dc

# Bright colors
bright0=3d444d
bright1=c96a6a
bright2=7ab87a
bright3=c9a84c
bright4=95a1aa
bright5=8a7ab8
bright6=5fb3b3
bright7=c8d4dc

[cursor]
style=beam
blink=yes