#################################################
#               auto start apps                 #
#################################################

# enable clipboard manager
exec wl-paste --watch cliphist store

# enable auto tiling
exec_always autotiling -l 2

# bar
exec_always pkill waybar; waybar

# dark mode
excec_always gsettings set $gnome-schema color-scheme 'prefer-dark'