#################################################
#                Output configuration           #
#################################################

# Monitor integrado
output eDP-1 {
    resolution 1920x1080
    position   0 0
    scale      1
}

# Monitor externo (cuando conectado)
output DP-1 {
    resolution 1920x1080
    position   1920 0
    scale      1
}

# You can get the names of your outputs by running: swaymsg -t get_outputs